{
  "uid" : "b13b238cc0c78f9e",
  "name" : "test_skip",
  "fullName" : "testcase.test_goto_page#test_skip",
  "historyId" : "e2680fae59f99e5fd47c3b866881db02",
  "time" : {
    "start" : 1685855982033,
    "stop" : 1685855982033,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "Skipped: unconditional skip",
  "statusTrace" : "('D:\\\\python_Code\\\\pythonProject\\\\pythonclasses\\\\autoclass\\\\day07\\\\appautotest\\\\testcase\\\\test_goto_page.py', 13, 'Skipped: unconditional skip')",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1685855982045,
      "stop" : 1685855982276,
      "duration" : 231
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "base_url",
    "time" : {
      "start" : 1685855982276,
      "stop" : 1685855982276,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "setup_teardown",
    "time" : {
      "start" : 1685855982277,
      "stop" : 1685856012331,
      "duration" : 30054
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\\Users\\syz\\AppData\\Local\\Temp\\202354-23592-12y2e5v.rcel\\appium-uiautomator2-server-v4.17.4.apk'. Original error: Exception in thread \"main\" java.lang.OutOfMemoryError\r\n\tat sun.misc.Unsafe.allocateMemory(Native Method)\r\n\tat java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)\r\n\tat java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)\r\n\tat com.android.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:102)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:384)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:434)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verifyJarEntriesAgainstManifestAndSigners(V1SchemeVerifier.java:1325)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.access$700(V1SchemeVerifier.java:84)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(V1SchemeVerifier.java:363)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(V1SchemeVerifier.java:204)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(V1SchemeVerifier.java:126)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:294)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:149)\r\n\tat com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)\r\n\tat com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\\Users\\syz\\AppData\\Local\\Temp\\202354-23592-12y2e5v.rcel\\appium-uiautomator2-server-v4.17.4.apk'. Original error: Exception in thread \"main\" java.lang.OutOfMemoryError\r\n\tat sun.misc.Unsafe.allocateMemory(Native Method)\r\n\tat java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)\r\n\tat java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)\r\n\tat com.android.apksig.internal.util.FileChannelDataSource.feed(FileChannelDataSource.java:102)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:384)\r\n\tat com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:434)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verifyJarEntriesAgainstManifestAndSigners(V1SchemeVerifier.java:1325)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.access$700(V1SchemeVerifier.java:84)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.verify(V1SchemeVerifier.java:363)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signers.access$100(V1SchemeVerifier.java:204)\r\n\tat com.android.apksig.internal.apk.v1.V1SchemeVerifier.verify(V1SchemeVerifier.java:126)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:294)\r\n\tat com.android.apksig.ApkVerifier.verify(ApkVerifier.java:149)\r\n\tat com.android.apksigner.ApkSignerTool.verify(ApkSignerTool.java:531)\r\n\tat com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:91)\r\n\n    at getResponseForW3CError (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n",
    "statusTrace" : "  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python_Code\\pythonProject\\pythonclasses\\autoclass\\day07\\appautotest\\conftest.py\", line 28, in setup_teardown\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", Caps.caps_for_xiaomishop)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 275, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  }, {
    "name" : "_verify_url",
    "time" : {
      "start" : 1685855982277,
      "stop" : 1685855982277,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "_skip_sensitive",
    "time" : {
      "start" : 1685855982277,
      "stop" : 1685855982277,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "sensitive_url",
    "time" : {
      "start" : 1685855982277,
      "stop" : 1685855982277,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.skip"
  }, {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_goto_page"
  }, {
    "name" : "host",
    "value" : "syzpc"
  }, {
    "name" : "thread",
    "value" : "12620-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_goto_page"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.skip" ]
  },
  "source" : "b13b238cc0c78f9e.json",
  "parameterValues" : [ ]
}